language: objective-c

sudo: required

compiler:
  - g++

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

before_install:
  - sudo brew update
  - clang -v
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - wget https://www.khronos.org/registry/cl/api/1.2/cl.hpp
  - sudo mv cl.hpp /System/Library/Frameworks/OpenCL.framework/Headers/cl.hpp
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - git clone http://github.com/cdeterman/RViennaCL.git
  - R CMD INSTALL RViennaCL/

install:
  - ./travis-tool.sh install_deps 

before_script:
  - R CMD INSTALL .

script:
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
